[project]
name = "reflexion-agent"
version = "0.1.0"
description = ""
authors = [
    {name = "Suraj Singh Karki",email = "surajkarki08@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "python-dotenv (>=1.2.4,<2.0.0)",
    "black (>=26.10.0,<27.0.0)",
    "isort (>=9.0.2,<10.0.0)",
    "langchain (>=1.4.3,<2.0.0)",
    "langchain-google-genai (>=4.4.0,<5.0.0)",
    "langgraph (>=1.2.14,<2.0.0)",
    "langchain-tavily (>=0.2.18,<0.3.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
